In [1]:
import numpy as np 

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2=np.array([[4,5,6],[7,8,9]])

In [5]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
a2.ndim

2

In [7]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [8]:
a3.ndim

3

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
ones=np.ones((2,3),)

In [14]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
ones_1=np.ones((3,3),int)

In [19]:
ones_1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
ones_1.dtype

dtype('int64')

In [21]:
zeros=np.zeros((2,3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
zeros_1=np.zeros((3,3),int)

In [25]:
zeros_1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
zeros_1.dtype

dtype('int64')

In [28]:
zeros_1.shape

(3, 3)

In [33]:
rand=np.arange(0,10,2)

In [34]:
rand

array([0, 2, 4, 6, 8])

In [36]:
rand_1=np.random.randint(1,8,size=(3,3))

In [37]:
rand_1

array([[4, 4, 1],
       [4, 3, 3],
       [2, 5, 4]], dtype=int32)

In [41]:
rand_2=np.random.randint(2,10,(3,3))

In [42]:
rand_2

array([[6, 4, 6],
       [3, 4, 5],
       [3, 5, 9]], dtype=int32)

In [57]:
np.random.seed(seed=9)
random_arry =np.random.randint(2,10,(3,3))
random_arry

array([[8, 6, 8],
       [7, 8, 2],
       [5, 8, 7]], dtype=int32)

In [58]:
np.random.seed(seed=9)
random_arry =np.random.randint(2,10,(3,3))
random_arry

array([[8, 6, 8],
       [7, 8, 2],
       [5, 8, 7]], dtype=int32)

In [77]:
random_arry1=np.random.random((3,4))

In [78]:
random_arry1

array([[0.55677515, 0.96293158, 0.71653299, 0.56824859],
       [0.78792439, 0.99191555, 0.03962933, 0.28143761],
       [0.6999809 , 0.14923921, 0.81248242, 0.02987414]])

In [80]:
random_arry1.reshape(4,3)

array([[0.55677515, 0.96293158, 0.71653299],
       [0.56824859, 0.78792439, 0.99191555],
       [0.03962933, 0.28143761, 0.6999809 ],
       [0.14923921, 0.81248242, 0.02987414]])